version: "3.5"

services:

  # base de données de l'application
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=appdb
      - POSTGRES_PASSWORD=appdb
      - POSTGRES_DB=appdb
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - appinternals
 
  # backend de l'application
  back:
    image: wns-deploy-angular-spring-back:latest
    depends_on:
      - db
    networks:
      - appinternals

  # frontend de l'application
  front:
    build: ./front
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production  
    tty: true
  
  # serveur web de façade qui va dispatcher les requêtes entre back et front (voir nginx.conf)
  nginx:
    image: nginx:1.21.3
    depends_on:
      - back
      - front
    restart: always
    networks:
      - appinternals
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/usr/share/nginx/html
      - ./logs:/var/log/nginx
volumes:
  web-client-build:
  db:
    driver: local
networks:
  appinternals:
    name: appinternals_local