version: "3.5"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=appdb
      - POSTGRES_PASSWORD=appdb
      - POSTGRES_DB=appdb
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - appinternals
  back:
    image: lgrignon/wns-deploy-angular-spring-back:latest
    #command: sh -c "npm run build && npm run prod"
    depends_on:
      - db
    
    networks:
      - appinternals
  front:
    build: ./front
    #command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production  
    tty: true
  nginx:
    image: nginx:1.21.3
    depends_on:
      - back
      - front
    restart: always
    networks:
      - appinternals
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  web-client-build:
  db:
    driver: local
networks:
  appinternals:
    name: appinternals_${GATEWAY_PORT:-8000}