name: Deploy to preprod

on:
  push:
    branches:
      - '**'
  # allow user to start job manually
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build FRONT image
        run: docker build -f deploy/Dockerfile-nginx-front -t lgrignon/wns-deploy-angular-spring-front:main .

      - name: Build BACK image with Maven
        working-directory: ./back
        run: ./mvnw --batch-mode --update-snapshots spring-boot:build-image -Dimage.tag=${GITHUB_REF##*/} "-Dimage.dockeruser=${{ secrets.DOCKERHUB_USERNAME }}"      

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Dump local images
        run: docker images
      
      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/wns-deploy-angular-spring-back:${GITHUB_REF##*/}
